Update alias.txt
VATGER-Nav/aliases pull request #21
Opened 2023-10-02 19:33 UTC by pascalgrotzke

AUTOTEXT MESSAGES fixed

2023-10-03 03:42 UTC, capzDE commented
Was war denn kaputt?

2023-10-03 06:27 UTC, hannesaltmann commented
> Was war denn kaputt?
Sink- und Steigflüge und Directs haben nicht korrekt oder gar nicht funktioniert. 

@pascalgrotzke wäre dennoch super, wenn wir bei der korrekten Phraseologie bleiben und nicht so einen Mischmasch, der hier vorgeschlagen wird.

2023-10-03 10:01 UTC, pascalgrotzke commented
@hannesaltmann 
Ich habe als Notfallreparatur erstmal einfach die Autotexte aus einem ganz alten Pack reinkopiert. Inhaltliche kann ich gerne nochmal drüber schauen.

2023-10-04 08:30 UTC, fpletz commented
Ich würde vorschlagen meinen ursprünglichen PR #5 wieder aufzugreifen. Der hatte IMHO korrekte Phraseo und hat funktioniert bevor er verschlimmbessert wurde.

2023-10-21 20:25 UTC, LeoKle commented
> Ich würde vorschlagen meinen ursprünglichen PR #5 wieder aufzugreifen. Der hatte IMHO korrekte Phraseo und hat funktioniert bevor er verschlimmbessert wurde.

wurde das nicht mit 21476a9 erledigt?

2023-10-28 16:04 UTC, capzDE commented
> > Ich würde vorschlagen meinen ursprünglichen PR #5 wieder aufzugreifen. Der hatte IMHO korrekte Phraseo und hat funktioniert bevor er verschlimmbessert wurde.
> 
> wurde das nicht mit [21476a9](https://github.com/VATGER-Nav/aliases/commit/21476a95dfebd0bc876bbb37f21449f7ca0a131e) erledigt?

Eigentlich ja, aber ich hab im Nachhinein irgendwann mal im Zuge eines unrelated issues/requests (finde es gerade nicht mehr, war aber glaub von JV) überall wo zutreffend die ganzen [built-in functions](https://www.euroscope.hu/wp/built-in-functions/) reingebastelt, auch bei den Autotext Messages - offenbar ist dabei dann was kaputt gegangen. Alles andere ist aber wie in FPs ursprünglichem PR #5, dementsprechend +1, den dann einfach wieder aufzugreifen.

2023-10-28 16:40 UTC, hannesaltmann requested changes
Phraseologie müsste angepasst werden.

2024-02-15 12:23 UTC, closed without merging